services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    image: myapp_image:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/app_production
      REDIS_URL: redis://redis:6379/0
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_HOST: backend.aalsaigh.com
      RAILS_PROTOCOL: https
      RAILS_ASSUME_SSL: "true"
      RAILS_FORCE_SSL: "true"
      PORT: "9003"
      SECRET_KEY_BASE: 4d69d803ba66234ffd67980c16dc3d62ff57dee4ce071db973b38e3925c380c6658719927e77fc8abffb871b04d53ec603df0d57c104c4949944f9267f9151c9
    volumes:
      - storage:/app/storage
    ports:
       - "9003:9003"  # Map host port 9001 to container port 9001
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p ${PORT:-9003}"]
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:${PORT:-9003}/up || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  sidekiq:
    image: myapp_image:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/app_production
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: 4d69d803ba66234ffd67980c16dc3d62ff57dee4ce071db973b38e3925c380c6658719927e77fc8abffb871b04d53ec603df0d57c104c4949944f9267f9151c9
    volumes:
      - storage:/app/storage
    command: ["bundle", "exec", "sidekiq"]

volumes:
  postgres_data:
  storage: